OpenLara modern RPI support
Exarkuniv/RetroPie-Extra pull request #179
Opened 2024-02-27 05:11 UTC by dborel

Added build script for OpenLara, using SDL and desktop GL for higher quality and modern RPI compatibility. In contrast, lr-openlara tries to use dispmanx and GLES2, which limit it to RPI3 and earlier and don't take full advantage of V3D's capabilities.

2024-03-01 15:16 UTC, Exarkuniv requested changes
one small thing to change

2024-03-01 15:16 UTC, Exarkuniv commented on scriptmodules/ports/openlara.sh
> +#
one thing is to change this. im going to be going through all my files and changing them all so they are all uniform

if you like you can add a line there with your name as the author so you get credit for it. not needed just a option

```suggestion
#!/usr/bin/env bash

# This file is part of RetroPie-Extra, a supplement to RetroPie.
# For more information, please visit:
#
# https://github.com/RetroPie/RetroPie-Setup
# https://github.com/Exarkuniv/RetroPie-Extra
#
# See the LICENSE file distributed with this source and at
# https://raw.githubusercontent.com/Exarkuniv/RetroPie-Extra/master/LICENSE
#
```
other then that it looks good. i installed it, but i dont have game files so ill take your work it works

2024-03-02 18:47 UTC, dborel commented
If you don't have an iso of the original PC cd-rom or GOG/Steam data, you can manually test with https://github.com/libretro/libretro-content/blob/master/Tomb%20Raider/Tomb%20Raider%20(Demo).zip. I left it out of the script because it lacks the menu, making it a bit harder to exit (it infinitely restarts the demo level when you try to quit).

2024-03-03 16:44 UTC, Exarkuniv reviewed
Looks good. Like I said if you want a line with marking you are author you can. But I'm good with it

I'm still learning how to review in GitHub 

I'll give the game files a try tomorrow. Thanks and yes best to leave it out since you can exit

2024-03-03 16:45 UTC, Exarkuniv approved these changes

2024-03-04 16:44 UTC, merged